---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: brigade-automation
  namespace: default
  labels:
    app: brigade-automation
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: automation-seed
  template:
    metadata:
      labels:
        app: automation-seed
        version: '0'
      annotations:
        atomist.com/k8vent: '{"webhooks":["https://webhook.atomist.com/atomist/kube/teams/TEAM_ID"]}'
        atomist.com/repo-image: '{"repo":{"owner":"mumoshu","name":"brigade-automation"},"image":"mumoshu/brigade-automation"}'
    spec:
      containers:
      - name: automation-seed
        image: mumoshu/brigade-automation:VERSION
        imagePullPolicy: IfNotPresent
        env:
        - name: ATOMIST_TEAM
          value: TEAM_ID
        - name: GITHUB_TOKEN
          value: YOUR_TOKEN
        ports:
        - name: http
          containerPort: 2866
          protocol: TCP
        livenessProbe:
          httpGet:
            path: "/health"
            port: 2866
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 3
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: "/health"
            port: 2866
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 3
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 0.5
            memory: 160Mi
          requests:
            cpu: 0.1
            memory: 128Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
