replicaCount: 1
image:
  repository: mumoshu/brigade-automation
  tag: canary
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 0.5
    memory: 160Mi
  requests:
    cpu: 0.1
    memory: 128Mi
owner: default-owner
env:
  ATOMIST_TEAM: MYATOMISTTEAM
  GITHUB_TOKEN: MYGITHUBTOKEN
